# Generated by Django 5.2.1 on 2025-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_futured',
            field=models.BooleanField(default=False),
        ),
    ]
