# Generated by Django 5.2.1 on 2025-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_services_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
