# Generated by Django 5.2.1 on 2025-05-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
