# Generated by Django 5.2.1 on 2025-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=100)),
                ('_description', models.TextField()),
                ('_iconClass', models.CharField(max_length=50)),
                ('_isFutured', models.BooleanField(default=False)),
                ('_slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['_title'],
            },
        ),
    ]
