# Generated by Django 5.2.1 on 2025-06-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['Title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='services',
            old_name='_description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='_iconClass',
            new_name='IconClass',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='_isFutured',
            new_name='IsFutured',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='_slug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='_title',
            new_name='Title',
        ),
    ]
