# Generated by Django 5.2.1 on 2025-06-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_services_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='IsFutured',
            new_name='IsFeatured',
        ),
    ]
